services:
  database:
    image: postgres:16
    container_name: library-database
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - library_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - library-network

  backend:
    build:
      context: ./library-backend
      dockerfile: Dockerfile

    container_name: library-backend
    restart: unless-stopped

    environment:
      DB_URI: jdbc:postgresql://database:${DB_PORT}/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}
      JPA_DDL_AUTO: ${JPA_DDL_AUTO}
      SHOW_SQL: ${SHOW_SQL}
      SERVER_PORT: ${BACKEND_PORT}

    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

    depends_on:
      database:
        condition: service_healthy

    networks:
      - library-network

  frontend:
    build:
      context: ./library-frontend
      dockerfile: Dockerfile

    container_name: library-frontend
    restart: unless-stopped

    ports:
      - "${FRONTEND_PORT}:80"

    depends_on:
      - backend

    networks:
      - library-network

volumes:
  library_postgres_data:

networks:
  library-network:
    driver: bridge