spring.application.name=library-backend
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URI:jdbc:postgresql://localhost:5432/library_db}
spring.datasource.username=${DB_USER:library_user}
spring.datasource.password=${DB_PASSWORD:library_password}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=${SHOW_SQL:false}

spring.jackson.default-property-inclusion=non_null

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
